# Generated by Django 3.2.6 on 2021-08-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrypt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='destination_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='destination_url',
        ),
        migrations.AddField(
            model_name='project',
            name='source_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='source_url',
            field=models.URLField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
