# Generated by Django 3.2.6 on 2021-08-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrypt', '0003_project_source_workbench'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='destination_workbench',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
