# Generated by Django 3.2.6 on 2021-09-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrypt', '0004_project_destination_workbench'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='source_url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
