# Generated by Django 3.2.6 on 2021-09-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrypt', '0005_alter_project_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='folder',
            field=models.FilePathField(allow_folders=True, default=1),
            preserve_default=False,
        ),
    ]
