# Generated by Django 3.2.6 on 2021-09-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrypt', '0006_project_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='folder',
            field=models.FilePathField(allow_folders=True, default='/repos'),
        ),
    ]
