# Generated by Django 3.2.6 on 2021-09-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrypt', '0007_alter_project_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='folder',
            field=models.CharField(default='/repos', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_url',
            field=models.URLField(max_length=255),
        ),
    ]
