# Generated by Django 3.2.6 on 2021-09-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrypt', '0008_auto_20210915_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='folder',
            field=models.CharField(default='repos/', max_length=255),
        ),
    ]
