# Generated by Django 3.0.8 on 2020-07-10 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('context', models.CharField(default='None', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('context', models.TextField(default=None)),
                ('iframe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.iFrame')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('silabus', models.CharField(max_length=2000)),
                ('certificate_example', models.CharField(max_length=2000)),
                ('date_of_start', models.DateField()),
                ('author', models.CharField(max_length=200)),
                ('goal', models.CharField(max_length=2000)),
                ('tasks', models.CharField(max_length=2000)),
                ('slag', models.CharField(max_length=2000)),
                ('reviews', models.CharField(max_length=2000)),
                ('lesson', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson')),
            ],
        ),
    ]
