# Generated by Django 3.0.8 on 2020-07-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('silabus', models.CharField(max_length=2000)),
                ('certificate_example', models.CharField(max_length=2000)),
                ('date_of_start', models.DateField()),
                ('author', models.CharField(max_length=200)),
                ('goal', models.CharField(max_length=2000)),
                ('tasks', models.CharField(max_length=2000)),
                ('slag', models.CharField(max_length=2000)),
                ('reviews', models.CharField(max_length=2000)),
            ],
        ),
    ]
